version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Entered the post_build phase...
      - mv target/tax-burden-web-0.0.1-SNAPSHOT.jar tax-burden-web-0.0.1-SNAPSHOT.jar
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - tax-burden-web-0.0.1-SNAPSHOT.jar
    - .ebextensions/**/*
  discard-paths: no
cache:
  paths:
    - '/root/.m2/**/*'