package com.ttb.service.taxburden.domain;

public enum TaxType {
	INCOME_FEDERAL,
	INCOME_STATE,
	PROPERTY_STATE,
	PROPERTY_COUNTY,
	PROPERTY_CITY,
	SALES_STATE,
	SALES_COUNTY,
	SALES_CITY,
	FUEL_FEDERAL,
	FUEL_STATE
	;
}