package com.ttb.service.taxburden.domain;

public enum TaxType {
	INCOME_FEDERAL,
	INCOME_STATE,
	INCOME_COUNTY,
	INCOME_CITY,
	PROPERTY_STATE,
	PROPERTY_COUNTY,
	PROPERTY_CITY,
	SALES_STATE,
	SALES_COUNTY,
	SALES_CITY,
	FUEL_FEDERAL,
	FUEL_STATE,
	PAYROLL_FEDERAL,
	PAYROLL_SELF_EMP_FEDERAL,
	PAYROLL_COUNTY,
	PAYROLL_CITY,
	CAPITAL_GAINS_FEDERAL
	;
}